# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgRes.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
try:
    import cv2
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
    from PyQt5.QtGui import QIcon
    from PyQt5.QtWidgets import QDialog, QListWidget,QLineEdit , QMessageBox , QVBoxLayout, QInputDialog,QPushButton, QHBoxLayout, QApplication
except:
    os.system('pip install opencv-python')
    os.system('pip install pyqt5')
finally:
    import cv2
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
    from PyQt5.QtGui import QIcon
    from PyQt5.QtWidgets import QDialog, QListWidget,QLineEdit , QMessageBox , QVBoxLayout, QInputDialog,QPushButton, QHBoxLayout, QApplication

class Ui_MainWindow9(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditw = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditw.setObjectName("lineEditw")
        self.gridLayout.addWidget(self.lineEditw, 3, 4, 1, 1)
        self.loh = QtWidgets.QLabel(self.centralwidget)
        self.loh.setObjectName("loh")
        self.gridLayout.addWidget(self.loh, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)
        self.lnew = QtWidgets.QLabel(self.centralwidget)
        self.lnew.setObjectName("lnew")
        self.gridLayout.addWidget(self.lnew, 2, 3, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.lnw = QtWidgets.QLabel(self.centralwidget)
        self.lnw.setObjectName("lnw")
        self.gridLayout.addWidget(self.lnw, 3, 3, 1, 1)
        self.lnh = QtWidgets.QLabel(self.centralwidget)
        self.lnh.setObjectName("lnh")
        self.gridLayout.addWidget(self.lnh, 4, 3, 1, 1)
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Avengeance")
        font.setPointSize(20)
        self.MainLabel.setFont(font)
        self.MainLabel.setAutoFillBackground(True)
        self.MainLabel.setScaledContents(True)
        self.MainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MainLabel.setObjectName("MainLabel")
        self.gridLayout.addWidget(self.MainLabel, 0, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 2, 3, 1)
        self.bresize = QtWidgets.QPushButton(self.centralwidget)
        self.bresize.setObjectName("bresize")
        self.gridLayout.addWidget(self.bresize, 5, 3, 1, 2)
        self.low = QtWidgets.QLabel(self.centralwidget)
        self.low.setObjectName("low")
        self.gridLayout.addWidget(self.low, 3, 0, 1, 1)
        self.lineEdith = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdith.setObjectName("lineEdith")
        self.gridLayout.addWidget(self.lineEdith, 4, 4, 1, 1)
        self.loriginal = QtWidgets.QLabel(self.centralwidget)
        self.loriginal.setObjectName("loriginal")
        self.gridLayout.addWidget(self.loriginal, 2, 0, 1, 2)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setAutoFillBackground(True)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropOverwriteMode(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 5)
        self.badd = QtWidgets.QPushButton(self.centralwidget)
        self.badd.setObjectName("badd")
        self.gridLayout.addWidget(self.badd, 5, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 357, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.badd.clicked.connect(self.addimg)
        self.bresize.clicked.connect(self.resizeimg)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image-Resizer"))
        self.lineEditw.setPlaceholderText(_translate("MainWindow", "Enter width in pixel"))
        self.loh.setText(_translate("MainWindow", "Height"))
        self.label_9.setText(_translate("MainWindow", "null"))
        self.lnew.setText(_translate("MainWindow", "New-Dimension"))
        self.label_8.setText(_translate("MainWindow", "null"))
        self.lnw.setText(_translate("MainWindow", "Width"))
        self.lnh.setText(_translate("MainWindow", "Height"))
        self.MainLabel.setText(_translate("MainWindow", "Image-Resizer"))
        self.bresize.setText(_translate("MainWindow", "Resize"))
        self.low.setText(_translate("MainWindow", "Width"))
        self.lineEdith.setPlaceholderText(_translate("MainWindow", "Enter height in pixel"))
        self.loriginal.setText(_translate("MainWindow", "Original-Dimension"))
        self.badd.setText(_translate("MainWindow", "Add Image"))
    List=[]

    def addimg(self):
        filename = QFileDialog.getOpenFileName()
        global path
        global img
        path = filename[0]
        img=cv2.imread(path)
        h,w,c=img.shape
        print(h,w,c)
        self.label_9.setText(str(h))
        self.label_8.setText(str(w))

        self.List.append(path)
        print(self.List)
        self.listWidget.addItem(path)

    def resizeimg(self):
        
        a=self.lineEdith.text()
        b=self.lineEditw.text()
        width,height=int(b),int(a)
        imgResize=cv2.resize(img,(width,height))
        newpath=path+"new.jpg"
        cv2.imwrite(newpath,imgResize)
        #imgCropped=img[0:900,300:540]
        print(imgResize.shape)
        cv2.imshow("Original",img)
        cv2.imshow("Resized",imgResize)
        #cv2.imshow("cloud Cropped",imgCropped)
        cv2.waitKey(0)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow9()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
